// <auto-generated />
namespace CAEProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddPsReply_And_AddNPInPs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPsReply_And_AddNPInPs));
        
        string IMigrationMetadata.Id
        {
            get { return "202011030253455_AddPsReply_And_AddNPInPs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
