// <auto-generated />
namespace CAEProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditRegistrationFormComNumberTypeIntToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditRegistrationFormComNumberTypeIntToString));
        
        string IMigrationMetadata.Id
        {
            get { return "202102050658236_Edit RegistrationForm ComNumber Type Int To String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
