// <auto-generated />
namespace CAEProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TrainingCourseAddApplicationStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrainingCourseAddApplicationStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202102020857273_TrainingCourse Add ApplicationStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
