// <auto-generated />
namespace CAEProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ResultsPublishAddSource : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResultsPublishAddSource));
        
        string IMigrationMetadata.Id
        {
            get { return "202101060617301_ResultsPublish Add Source"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
